<a href="https://colab.research.google.com/github/utyabia/1-notebook/blob/main/PyTorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. Create a random tensor with shape (7, 7)

In [3]:
import torch

tensor_a = torch.rand(7, 7)
print(tensor_a)


tensor([[0.3218, 0.5026, 0.6148, 0.0543, 0.6533, 0.9448, 0.3586],
        [0.7917, 0.0577, 0.7790, 0.5326, 0.6528, 0.6448, 0.9127],
        [0.0657, 0.6765, 0.6364, 0.0324, 0.2456, 0.0576, 0.8672],
        [0.4130, 0.4502, 0.4313, 0.5167, 0.1473, 0.3878, 0.5083],
        [0.1002, 0.2132, 0.5607, 0.5983, 0.2617, 0.4717, 0.2544],
        [0.4913, 0.0421, 0.3080, 0.7293, 0.1481, 0.9424, 0.9993],
        [0.7319, 0.8452, 0.3141, 0.6806, 0.7916, 0.8001, 0.2392]])


3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
tensor_b = torch.rand(1, 7)
output_3 = torch.matmul(tensor_a, tensor_b.T)
print(output_3)


tensor([[1.9260],
        [2.2680],
        [1.1314],
        [1.4271],
        [1.0943],
        [1.7252],
        [2.5592]])


4. Set the random seed to 0 and do 2 & 3 over again.

In [5]:
torch.manual_seed(0)

tensor_a = torch.rand(7, 7)
tensor_b = torch.rand(1, 7)
output_4 = torch.matmul(tensor_a, tensor_b.T)

print(output_4, output_4.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [6]:
torch.cuda.manual_seed(1234)


6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [7]:
torch.manual_seed(1234)

if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

tensor_gpu_a = torch.rand(2, 3).to(device)
tensor_gpu_b = torch.rand(2, 3).to(device)

print("Device:", device)
print(tensor_gpu_a)
print(tensor_gpu_b)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [8]:
output_7 = torch.matmul(tensor_gpu_a, tensor_gpu_b.T)
print(output_7, output_7.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


8. Find the maximum and minimum values of the output of 7.

In [9]:
print("Max value:", output_7.max())
print("Min value:", output_7.min())


Max value: tensor(0.5617)
Min value: tensor(0.3647)


9. Find the maximum and minimum index values of the output of 7.

In [11]:
max_pos = torch.nonzero(output_7 == output_7.max(), as_tuple=False)
min_pos = torch.nonzero(output_7 == output_7.min(), as_tuple=False)

print("Position of max value (row, col):", max_pos[0].tolist())
print("Position of min value (row, col):", min_pos[0].tolist())


Position of max value (row, col): [1, 1]
Position of min value (row, col): [0, 0]


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [10]:
torch.manual_seed(7)

tensor_10 = torch.rand(1, 1, 1, 10)
tensor_10_squeezed = tensor_10.squeeze()

print(tensor_10, tensor_10.shape)
print(tensor_10_squeezed, tensor_10_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
